"""empty message

Revision ID: 2bbfa5145834
Revises: 28acc45a619e
Create Date: 2023-09-15 19:18:21.827480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bbfa5145834'
down_revision = '28acc45a619e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especialidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialista_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'especialistas', ['especialista_id'], ['id'])

    with op.batch_alter_table('especialistas', schema=None) as batch_op:
        batch_op.drop_constraint('especialistas_ibfk_1', type_='foreignkey')
        batch_op.drop_column('especialidad_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especialistas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialidad_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('especialistas_ibfk_1', 'especialidad', ['especialidad_id'], ['id'])

    with op.batch_alter_table('especialidad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('especialista_id')

    # ### end Alembic commands ###
